AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  CompanyName:
    Type: String
  SenderEmail:
    Type: String
  StripeSecretKey:
    Type: String
  StripePublishableKey:
    Type: String
  Environment:
    Type: String
  ProjectName:
    Type: String
  ProjectId:
    Type: String
  ThemeName:
    Type: String

Globals:
  Function:
    Environment:
      Variables:
        PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable
        COMPANY_NAME: !Ref 'CompanyName'
        SENDER_EMAIL: !Ref 'SenderEmail'
        CLIENT_ID: !Ref 'CognitoUserPoolClient'
        USER_POOL_ID: !Ref 'CognitoUserPool'
        STRIPE_SECRET_KEY : !Ref 'StripeSecretKey'
        STRIPE_PUBLISHABLE_KEY : !Ref 'StripePublishableKey'
        STAGE_NAME : !Ref 'Environment'
        BASE_URL: http://example.com
        REGION: us-east-1
        ASSETS_HOST: !Join ['/', ['https://s3.amazonaws.com',!Ref 'S3AssetsBucket' ] ]
        THEME_NAME: !Ref 'ThemeName'

Resources:

  S3AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub ${Environment}.assets.${ProjectName}

  PaymentRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', [!Ref 'ProjectName', !Ref 'Environment']]
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: created_at
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: created_at
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Join ['-', [!Ref 'ProjectName', !Ref 'Environment']]
  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Join ['', ['PaymentDriver', !Ref 'Environment']]
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows: [ADMIN_NO_SRP_AUTH]
  CognitoIdPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: !Join ['', ['PaymentDriver', !Ref 'Environment']]
      CognitoIdentityProviders:
        -
          ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName
      AllowUnauthenticatedIdentities: false

  Home:
    Type: AWS::Serverless::Function
    Properties:
      Handler: home.index
      Runtime: nodejs8.10
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  Login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: home.login
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute
       - AmazonDynamoDBFullAccess
       - Version: '2012-10-17'
         Statement:
           - Effect: Allow
             Action:
               - cognito-idp:*
             Resource: !GetAtt CognitoUserPool.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /login
            Method: post

  Logout:
    Type: AWS::Serverless::Function
    Properties:
      Handler: home.logout
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /logout
            Method: get

  PaymentRequests:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.index
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - AmazonDynamoDBFullAccess
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: get

  PaymentRequestsNew:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.new
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - AmazonDynamoDBFullAccess
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests-new
            Method: get

  PostPaymentRequest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.post
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - AmazonDynamoDBFullAccess
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: post

  ResendPaymentRequest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.resend
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - AmazonDynamoDBFullAccess
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - ses:*
             Resource: *
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests-resend
            Method: get

  PaymentForm:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payments.get
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: get

  ProcessPayment:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payments.post
      Runtime: nodejs8.10
      Policies:
       - AWSLambdaExecute # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - s3:GetObject
               - s3:GetObjectACL
             Resource: 'arn:aws:s3:::my-bucket/*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: post

Outputs:
  AssetsUrl:
    Value: !GetAtt S3AssetsBucket.WebsiteURL
    Description: URL for the S3 bucket.
  AssetsLogicAddress:
    Value: !Ref S3AssetsBucket
    Description: URL for the S3 bucket.
