AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  PaymentRequests:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.get
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: get
  PaymentForm:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payments.get
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: get
      Environment:
        Variables:
          STRIPE_PUBLISHABLE_KEY: publishable
  ProcessPayment:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payments.post
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: post
      Environment:
        Variables:
          STRIPE_SECRET_KEY: secret