AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 180
    Handler: index.handler
    Environment:
      Variables:
        AWS_REGION: us-east-1
        COMPANY_NAME: Payment Driver
        SENDER_EMAIL: Payment Driver <payments@example.com>
        BASE_URL: http://example.com
        CLIENT_ID: client_id
        USER_POOL_ID: user_pool_id
        REGION: us-east-1
        STRIPE_SECRET_KEY: stripe_secret
        STRIPE_PUBLISHABLE_KEY: stripe_publishable

Resources:

  PaymentRequestsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: id
         Type: String

  Home:
    Type: AWS::Serverless::Function
    Properties:
      Handler: home.index
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  Login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: home.login
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /login
            Method: post

  Logout:
    Type: AWS::Serverless::Function
    Properties:
      Handler: home.logout
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /logout
            Method: get

  PaymentRequests:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.index
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: get
      Environment:
        Variables:
          PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable

  PaymentRequestsNew:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.new
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests-new
            Method: get
      Environment:
        Variables:
          PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable

  PostPaymentRequest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.post
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: post
      Environment:
        Variables:
          PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable

  ResendPaymentRequest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment-requests.resend
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payment-requests-resend
            Method: get
      Environment:
        Variables:
          PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable

  PaymentForm:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payments.get
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: get
      Environment:
        Variables:
          PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable

  ProcessPayment:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payments.post
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: post
      Environment:
        Variables:
          PAYMENT_REQUESTS_TABLE_NAME: !Ref PaymentRequestsTable